# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nathandyer.me" # the base hostname & protocol for your site
timezone: "America/New_York"

# Meta
title: Nathan Dyer
avatar: avatar.png
gravatar: b914ca7c5324480b1da84eef179b2727
description: "A website with blog posts and pages" # used by search engines

# Localization strings
str_follow_on: "Follow on"
str_rss_follow: "Follow RSS feed"
str_email: "Email"
str_next: "Next"
str_prev: "Prev"
str_continue_reading: "Continue reading"

# BUILD SETTINGS
markdown: kramdown
